export const INGREDIENTS: string[] = [
  // Warzywa
  "pomidor",
  "cebula",
  "czosnek",
  "marchew",
  "ziemniaki",
  "papryka",
  "papryka czerwona",
  "papryka żółta",
  "papryka zielona",
  "cukinia",
  "bakłażan",
  "szpinak",
  "sałata",
  "kapusta",
  "brokuły",
  "kalafior",
  "por",
  "seler",
  "pietruszka",
  "rzodkiewka",
  "ogórek",
  "dynia",
  "groszek",
  "fasola",
  "ciecierzyca",
  "kukurydza",
  "szparagi",
  // Białka
  "kurczak",
  "pierś z kurczaka",
  "udo kurczaka",
  "wołowina",
  "wieprzowina",
  "boczek",
  "szynka",
  "łosoś",
  "tuńczyk",
  "dorsz",
  "krewetki",
  "jajka",
  "tofu",
  // Nabiał
  "mleko",
  "masło",
  "ser żółty",
  "ser biały",
  "parmezan",
  "mozzarella",
  "feta",
  "śmietana",
  "jogurt",
  "śmietanka",
  // Pieczywo i zboża
  "chleb",
  "bułka",
  "makaron",
  "ryż",
  "kasza",
  "płatki owsiane",
  "quinoa",
  "mąka pszenna",
  "mąka kukurydziana",
  // Przyprawy i dodatki
  "sól",
  "pieprz",
  "oliwa z oliwek",
  "olej",
  "ocet",
  "musztarda",
  "ketchup",
  "majonez",
  "sos sojowy",
  "miód",
  "cukier",
  "cynamon",
  "papryka wędzona",
  "kurkuma",
  "curry",
  "oregano",
  "bazylia",
  "tymianek",
  "rozmaryn",
  "koperek",
  "natka pietruszki",
  "liść laurowy",
  "ziele angielskie",
  "imbir",
  "chilli",
  // Owoce
  "jabłko",
  "banan",
  "cytryna",
  "pomarańcza",
  "limonka",
  "truskawki",
  "maliny",
  "borówki",
  "awokado",
  // Inne
  "bulion",
  "passata pomidorowa",
  "puszka pomidorów",
  "mleko kokosowe",
  "soczewica",
  "orzechy włoskie",
  "migdały",
  "rodzynki",
];
